'use client';

import { montserrat } from '@/utils/fonts';
import Navbar from "@/components/navbar/navbar";
import Footer from '@/components/footer/footer';
import { useEffect, useState } from 'react';

import "./globals.css";

const navbarLinks = [
  { name: "Home", url: "#hero" },
  { name: "About", url: "#about" },
  { name: "Education", url: "#education" },
  { name: "Skills", url: "#skills" },
  { name: "Services", url: "#services" },
];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    setHydrated(true);
  }, []);

  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
        style={hydrated ? { paddingTop: '80px' } : undefined}
      >
        <Navbar links={navbarLinks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}

